# File: templates/deployment.yaml
# Kubernetes Deployment templates for all services

{{/*
Hello Service Deployment
*/}}
{{- if .Values.helloService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-microservices.helloService.fullname" . }}
  labels:
    {{- include "mern-microservices.helloService.labels" . | nindent 4 }}
  {{- with (merge .Values.helloService.podAnnotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.helloService.replicaCount }}
  selector:
    matchLabels:
      {{- include "mern-microservices.helloService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mern-microservices.helloService.selectorLabels" . | nindent 8 }}
      {{- with (merge .Values.helloService.podAnnotations .Values.commonAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "mern-microservices.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mern-microservices.serviceAccountName" . }}
      securityContext:
        {{- toYaml (default .Values.podSecurityContext .Values.helloService.podSecurityContext) | nindent 8 }}
      containers:
        - name: hello-service
          securityContext:
            {{- toYaml (default .Values.securityContext .Values.helloService.securityContext) | nindent 12 }}
          image: {{ include "mern-microservices.image" (dict "tag" .Values.helloService.image.tag "Values" .Values) }}
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.helloService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.helloService.service.targetPort }}
              protocol: TCP
          env:
            {{- include "mern-microservices.env" .Values.helloService | nindent 12 }}
          {{- if .Values.helloService.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.helloService.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.helloService.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.helloService.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.helloService.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.helloService.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.helloService.healthCheck.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: {{ .Values.helloService.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.helloService.healthCheck.failureThreshold }}
          {{- end }}
          {{- include "mern-microservices.resources" .Values.helloService | nindent 10 }}
      {{- with (default .Values.nodeSelector .Values.helloService.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.affinity .Values.helloService.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.tolerations .Values.helloService.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{/*
Profile Service Deployment
*/}}
{{- if .Values.profileService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-microservices.profileService.fullname" . }}
  labels:
    {{- include "mern-microservices.profileService.labels" . | nindent 4 }}
  {{- with (merge .Values.profileService.podAnnotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.profileService.replicaCount }}
  selector:
    matchLabels:
      {{- include "mern-microservices.profileService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mern-microservices.profileService.selectorLabels" . | nindent 8 }}
      {{- with (merge .Values.profileService.podAnnotations .Values.commonAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "mern-microservices.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mern-microservices.serviceAccountName" . }}
      securityContext:
        {{- toYaml (default .Values.podSecurityContext .Values.profileService.podSecurityContext) | nindent 8 }}
      containers:
        - name: profile-service
          securityContext:
            {{- toYaml (default .Values.securityContext .Values.profileService.securityContext) | nindent 12 }}
          image: {{ include "mern-microservices.image" (dict "tag" .Values.profileService.image.tag "Values" .Values) }}
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.profileService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.profileService.service.targetPort }}
              protocol: TCP
          env:
            {{- include "mern-microservices.env" .Values.profileService | nindent 12 }}
            {{- if and .Values.mongodb.connectionString .Values.mongodb.createSecret }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secretName }}
                  key: connection-string
            {{- end }}
          {{- if .Values.profileService.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.profileService.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.profileService.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.profileService.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.profileService.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.profileService.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.profileService.healthCheck.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: {{ .Values.profileService.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.profileService.healthCheck.failureThreshold }}
          {{- end }}
          {{- include "mern-microservices.resources" .Values.profileService | nindent 10 }}
      {{- with (default .Values.nodeSelector .Values.profileService.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.affinity .Values.profileService.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.tolerations .Values.profileService.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{/*
Frontend Deployment
*/}}
{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-microservices.frontend.fullname" . }}
  labels:
    {{- include "mern-microservices.frontend.labels" . | nindent 4 }}
  {{- with (merge .Values.frontend.podAnnotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "mern-microservices.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mern-microservices.frontend.selectorLabels" . | nindent 8 }}
      {{- with (merge .Values.frontend.podAnnotations .Values.commonAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "mern-microservices.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mern-microservices.serviceAccountName" . }}
      securityContext:
        {{- toYaml (default .Values.podSecurityContext .Values.frontend.podSecurityContext) | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml (default .Values.securityContext .Values.frontend.securityContext) | nindent 12 }}
          image: {{ include "mern-microservices.image" (dict "tag" .Values.frontend.image.tag "Values" .Values) }}
          imagePullPolicy: {{ default .Values.global.pullPolicy .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            {{- include "mern-microservices.env" .Values.frontend | nindent 12 }}
          {{- if .Values.frontend.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: {{ .Values.frontend.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.healthCheck.failureThreshold }}
          {{- end }}
          {{- include "mern-microservices.resources" .Values.frontend | nindent 10 }}
      {{- with (default .Values.nodeSelector .Values.frontend.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.affinity .Values.frontend.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.tolerations .Values.frontend.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}