# File: templates/secret.yaml
# Kubernetes Secret for MongoDB connection string

{{- if and .Values.mongodb.connectionString .Values.mongodb.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secretName }}
  labels:
    {{- include "mern-microservices.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # MongoDB connection string (base64 encoded)
  connection-string: {{ .Values.mongodb.connectionString | b64enc | quote }}
{{- else if not .Values.mongodb.createSecret }}
# MongoDB secret is managed externally
# Make sure to create the secret manually:
# kubectl create secret generic {{ .Values.mongodb.secretName }} \
#   --from-literal=connection-string="your-mongodb-connection-string"
{{- else }}
# MongoDB connection string not provided
# Set it at runtime using:
# --set mongodb.connectionString="your-connection-string"
{{- end }}