# File: templates/serviceaccount.yaml
# Kubernetes ServiceAccount for the application

{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mern-microservices.serviceAccountName" . }}
  labels:
    {{- include "mern-microservices.labels" . | nindent 4 }}
  {{- with (merge .Values.serviceAccount.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}