apiVersion: v1
kind: Service
metadata:
  name: backend-helloservice
  namespace: mern
spec:
  selector:
    app: backend-helloservice
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
